name: Test Python TDD example

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MQTT_BROKER: ${{ secrets.MQTT_BROKER }}
      MQTT_PORT: ${{ secrets.MQTT_PORT }}
      MQTT_TOPIC: ${{ secrets.MQTT_TOPIC }}
      MQTT_CLIENT_ID_PUBLISHER: ${{ secrets.MQTT_CLIENT_ID_PUBLISHER }}
      MQTT_CLIENT_ID_SUBSCRIBER: ${{ secrets.MQTT_CLIENT_ID_SUBSCRIBER }}
      MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
      MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies from setup.cfg
      run: |
        pip install --upgrade pip
        pip install .
      working-directory: ./ponderada-4/pyTdd

    - name: Clean up Python bytecode
      run: find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
    
    - name: Run tests
      run: pytest
